<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfg</string>
	</array>
	<key>name</key>
	<string>Nagios</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string># comments</string>
			<key>match</key>
			<string>^[\s]*#.*</string>
			<key>name</key>
			<string>comment.line.number-sign.nagios</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^[\s]*(define)[\s]+([A-Za-z0-9_]+)[\s]*(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.nagios</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.nagios</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character.nagios</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.character.nagios</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.name.section.nagios</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#separator</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.variable.nagios</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^[\s]*use[\s]+([A-Za-z0-9_-]+)</string>
					<key>name</key>
					<string>keyword.other.nagios</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^[\s]*[A-Za-z0-9_]+[\s]</string>
					<key>name</key>
					<string>keyword.other.nagios</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>In-line comments</string>
					<key>match</key>
					<string>;.*</string>
					<key>name</key>
					<string>comment.line.semi-colon.nagios</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.nagios</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.nagios</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#separator</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>separator</key>
		<dict>
			<key>comment</key>
			<string>check_command separators</string>
			<key>match</key>
			<string>!</string>
			<key>name</key>
			<string>constant.character.nagios</string>
		</dict>
		<key>variable</key>
		<dict>
			<key>comment</key>
			<string>Variables like $SERVICESTATE$, $USER1$ etc</string>
			<key>match</key>
			<string>\$([A-Za-z][A-Za-z0-9_]+)\$</string>
			<key>name</key>
			<string>support.variable.nagios</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.nagios</string>
	<key>uuid</key>
	<string>a8870a27-4f36-4aa7-8f7b-34a87060247d</string>
</dict>
</plist>
